//! macOS reliable paste.
//!
//! Publishes the transcript with `declareTypes:owner:`, which puts a *promise*
//! on the general pasteboard instead of data. When any consumer actually
//! requests the text, AppKit calls `pasteboard:provideDataForType:` on our
//! owner object — that callback is the read receipt. The previous clipboard is
//! restored once receipts go quiet (see `paste_tx::evaluate`), guarded by the
//! pasteboard `changeCount` so we never clobber a newer user copy.
//!
//! Threading: publishing and chord injection happen on the calling (main)
//! thread, because promised pasteboard data is serviced by AppKit on the main
//! run loop. The (potentially seconds-long) wait runs on a worker thread; the
//! guarded restore is dispatched back to the main thread.

use std::sync::{Arc, Mutex};
use std::thread;
use std::time::{Duration, Instant};

use log::{error, info};
use objc2::rc::Retained;
use objc2::runtime::ProtocolObject;
use objc2::{define_class, msg_send, AnyThread, DefinedClass};
use objc2_app_kit::{NSPasteboard, NSPasteboardItem, NSPasteboardTypeString, NSPasteboardWriting};
use objc2_foundation::{NSArray, NSData, NSInteger, NSObject, NSString};
use tauri::{AppHandle, Manager};
use tauri_plugin_clipboard_manager::ClipboardExt;

use super::{
    capture_snapshot, evaluate, guarded_dispatch, restore_if_owned, send_chord, ClipboardSnapshot,
    HistoryPasteOutcome, PasteCompletion, TxState, WaitDecision,
};
use crate::clipboard::send_return_key;
use crate::input::EnigoState;
use crate::settings::{AutoSubmitKey, ClipboardHandling, PasteMethod};

/// Concealment marker types declared alongside the text so that well-behaved
/// third-party clipboard managers (Maccy, Paste, ...) skip the transcript.
/// Fewer eager readers means a receipt is more likely to be the actual target.
/// These are conventions; nothing enforces them.
const CONCEALMENT_TYPES: [&str; 3] = [
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
];

pub struct ProviderIvars {
    state: Arc<Mutex<TxState>>,
    text: String,
}

define_class!(
    // SAFETY: NSObject has no subclassing requirements and the ivars are
    // plain Rust values guarded by a Mutex.
    #[unsafe(super(NSObject))]
    #[name = "HandyPasteProvider"]
    #[ivars = ProviderIvars]
    pub struct HandyPasteProvider;

    impl HandyPasteProvider {
        // NSPasteboardOwner informal protocol: the pasteboard is asking for the
        // promised data — our receipt that a consumer read the clipboard.
        #[unsafe(method(pasteboard:provideDataForType:))]
        fn pasteboard_provide_data_for_type(&self, pasteboard: &NSPasteboard, data_type: &NSString) {
            let ivars = self.ivars();
            // SAFETY: NSPasteboardTypeString is a read-only framework static.
            let is_text = unsafe { data_type.isEqualToString(NSPasteboardTypeString) };
            // Only a text read counts as a receipt: a request for one of the
            // concealment marker types is a clipboard manager inspecting the
            // markers, not the paste target reading the transcript.
            if is_text {
                if let Ok(mut state) = ivars.state.lock() {
                    state.record_receipt(Instant::now());
                }
            }
            let payload = if is_text {
                NSString::from_str(&ivars.text)
            } else {
                // Concealment marker types are never handed out.
                NSString::from_str("")
            };
            let _ = pasteboard.setString_forType(&payload, data_type);
        }

        #[unsafe(method(pasteboardChangedOwner:))]
        fn pasteboard_changed_owner(&self, _pasteboard: &NSPasteboard) {
            if let Ok(mut state) = self.ivars().state.lock() {
                state.ownership_lost = true;
            }
        }
    }
);

impl HandyPasteProvider {
    fn new(state: Arc<Mutex<TxState>>, text: String) -> Retained<Self> {
        let this = Self::alloc().set_ivars(ProviderIvars { state, text });
        unsafe { msg_send![super(this), init] }
    }
}

struct MacPending {
    permission_epoch: u64,
    state: Arc<Mutex<TxState>>,
    snapshot: ClipboardSnapshot,
    change_count: NSInteger,
    provider: Option<Retained<HandyPasteProvider>>,
    auto_submit: bool,
    auto_submit_key: AutoSubmitKey,
    /// ClipboardHandling::CopyToClipboard — instead of restoring, settle by
    /// re-writing the transcript as plain text (without the concealment
    /// markers), so clipboard managers record it and it outlives the promise.
    preserve_transcript: bool,
    /// The transcript, for the `preserve_transcript` re-write at settle time.
    transcript: String,
    settled: bool,
}

/// The transaction currently holding the clipboard, if any. A new paste
/// settles it before snapshotting (see `flush_pending`).
static PENDING: Mutex<Option<Arc<Mutex<MacPending>>>> = Mutex::new(None);

fn snapshot(pasteboard: &NSPasteboard) -> Result<ClipboardSnapshot, String> {
    capture_snapshot(
        || pasteboard.changeCount(),
        || {
            let Some(items) = pasteboard.pasteboardItems() else {
                // 无 items 但有 legacy 类型时不能把未知内容当空剪贴板。
                if pasteboard.types().is_some_and(|types| !types.is_empty()) {
                    return Err("pasteboard items unavailable for non-empty clipboard".into());
                }
                return Ok(Vec::new());
            };
            items
                .iter()
                .map(|item| {
                    item.types()
                        .iter()
                        .map(|kind| {
                            // 请求每个延迟表示并复制原始字节；任一无法兑现则不修改剪贴板。
                            let data = item.dataForType(&kind).ok_or_else(|| {
                                format!("clipboard representation unavailable: {kind}")
                            })?;
                            Ok((kind.to_string(), data.to_vec()))
                        })
                        .collect()
                })
                .collect()
        },
    )
}

fn prepare_items(snapshot: &ClipboardSnapshot) -> Result<Vec<Retained<NSPasteboardItem>>, String> {
    let mut restored = Vec::new();
    for formats in &snapshot.items {
        let item = NSPasteboardItem::new();
        for (kind, bytes) in formats {
            if !item.setData_forType(&NSData::from_vec(bytes.clone()), &NSString::from_str(kind)) {
                return Err(format!("cannot prepare clipboard representation: {kind}"));
            }
        }
        restored.push(item);
    }
    Ok(restored)
}

fn restore_snapshot(
    pasteboard: &NSPasteboard,
    snapshot: &ClipboardSnapshot,
    expected: NSInteger,
) -> Result<bool, String> {
    // 在 ownership 检查前完成全部分配和格式准备，缩短检查与替换之间的窗口。
    let restored: Vec<Retained<ProtocolObject<dyn NSPasteboardWriting>>> = prepare_items(snapshot)?
        .into_iter()
        .map(ProtocolObject::from_retained)
        .collect();
    let restored = NSArray::from_retained_slice(&restored);
    restore_if_owned(
        expected,
        || pasteboard.changeCount(),
        || {
            let cleared = pasteboard.clearContents();
            // AppKit 没有 compare-and-swap；clear 后若又被复制覆盖，绝不继续写回。
            if pasteboard.changeCount() != cleared {
                return Err("clipboard ownership changed during restore".into());
            }
            if !restored.is_empty() && !pasteboard.writeObjects(&restored) {
                return Err("failed to restore complete clipboard items".into());
            }
            Ok(())
        },
    )
}

/// 显式复制：全部原生对象准备好后才核验许可，不经过插件锁或隐式图像转换。
pub(crate) fn publish_snapshot(
    snapshot: ClipboardSnapshot,
    validate: impl FnOnce() -> Result<(), String>,
) -> HistoryPasteOutcome {
    publish_snapshot_on(&NSPasteboard::generalPasteboard(), snapshot, validate)
}

fn publish_snapshot_on(
    pasteboard: &NSPasteboard,
    snapshot: ClipboardSnapshot,
    validate: impl FnOnce() -> Result<(), String>,
) -> HistoryPasteOutcome {
    let prepared = match prepare_items(&snapshot) {
        Ok(items) => items
            .into_iter()
            .map(ProtocolObject::from_retained)
            .collect::<Vec<Retained<ProtocolObject<dyn NSPasteboardWriting>>>>(),
        Err(error) => return HistoryPasteOutcome::NotDispatched(error),
    };
    let objects = NSArray::from_retained_slice(&prepared);
    if pasteboard.changeCount() != snapshot.change_count {
        return HistoryPasteOutcome::NotDispatched(
            "clipboard changed during copy preparation".into(),
        );
    }
    if let Err(error) = validate() {
        return HistoryPasteOutcome::NotDispatched(error);
    }
    if pasteboard.changeCount() != snapshot.change_count {
        return HistoryPasteOutcome::NotDispatched(
            "clipboard changed during permission check".into(),
        );
    }
    let cleared = pasteboard.clearContents();
    if pasteboard.changeCount() != cleared || !pasteboard.writeObjects(&objects) {
        return HistoryPasteOutcome::PossiblyDispatched(
            "clipboard publication outcome unknown".into(),
        );
    }
    HistoryPasteOutcome::Dispatched
}

/// Settles a transaction exactly once: sends the owed auto-submit Enter and
/// restores the previous clipboard, guarded so we never clobber a newer copy.
/// Must run on the main thread. Uses the already-locked enigo when called
/// from within `paste` (which holds the lock), otherwise locks it itself.
fn settle(
    pending: &Arc<Mutex<MacPending>>,
    app_handle: &AppHandle,
    enigo: Option<&mut enigo::Enigo>,
) {
    let mut p = match pending.lock() {
        Ok(p) => p,
        Err(_) => return,
    };
    if p.settled {
        return;
    }
    p.settled = true;

    let (receipt_seen, ownership_lost) = match p.state.lock() {
        Ok(st) => (st.any_receipt_after_injection(), st.ownership_lost),
        Err(_) => (false, true),
    };

    // Auto-submit only once the target demonstrably read the transcript;
    // pressing Enter after an unconfirmed paste could submit stale content.
    if p.auto_submit
        && receipt_seen
        && crate::input_permission::check_epoch(p.permission_epoch).is_ok()
    {
        match enigo {
            Some(e) => {
                let _ = send_return_key(e, p.auto_submit_key);
            }
            None => {
                if let Some(enigo_state) = app_handle.try_state::<EnigoState>() {
                    if let Ok(mut e) = enigo_state.0.lock() {
                        if let Some(e) = e.as_mut() {
                            let _ = send_return_key(e, p.auto_submit_key);
                        }
                    }
                }
            }
        }
    }

    let still_ours =
        !ownership_lost && NSPasteboard::generalPasteboard().changeCount() == p.change_count;
    if !still_ours {
        info!("[reliable-paste] clipboard changed externally; leaving it untouched");
    } else if p.preserve_transcript {
        // The user asked for the transcript to stay on the clipboard: replace
        // the concealed promise with plain text so clipboard managers record
        // it and it survives this app exiting.
        let _ = app_handle.clipboard().write_text(&p.transcript);
        info!("[reliable-paste] left transcript on clipboard as plain text");
    } else {
        match restore_snapshot(
            &NSPasteboard::generalPasteboard(),
            &p.snapshot,
            p.change_count,
        ) {
            Ok(true) => info!("[reliable-paste] restored all previous clipboard items/types"),
            Ok(false) => info!("[reliable-paste] clipboard changed during restore preparation"),
            Err(error) => error!("[reliable-paste] complete clipboard restore failed: {error}"),
        }
    }

    // Release the owner; any outstanding promise dies with the pasteboard
    // contents we just replaced (or with the external change).
    p.provider = None;
}

/// If a previous transaction is still holding the clipboard, settle it now so
/// the caller's snapshot captures the user's original clipboard content.
fn flush_pending(app_handle: &AppHandle, enigo: &mut enigo::Enigo) {
    let previous = match PENDING.lock() {
        Ok(mut slot) => slot.take(),
        Err(_) => None,
    };
    if let Some(previous) = previous {
        settle(&previous, app_handle, Some(enigo));
    }
}

fn spawn_waiter(pending: Arc<Mutex<MacPending>>, app_handle: AppHandle) {
    thread::spawn(move || {
        let outcome = loop {
            thread::sleep(Duration::from_millis(15));
            let (decision, state_snapshot) = {
                let p = match pending.lock() {
                    Ok(p) => p,
                    Err(_) => return,
                };
                if p.settled {
                    // A newer paste settled this transaction already.
                    return;
                }
                let result = match p.state.lock() {
                    Ok(st) => {
                        let now = Instant::now();
                        let snapshot = (
                            st.any_receipt_after_injection(),
                            st.ownership_lost,
                            st.injection_failed,
                        );
                        (evaluate(&st, now), snapshot)
                    }
                    Err(_) => return,
                };
                result
            };
            if let WaitDecision::Finish = decision {
                break state_snapshot;
            }
        };

        let (receipt_seen, ownership_lost, injection_failed) = outcome;
        if ownership_lost {
            info!("[reliable-paste] settling: clipboard ownership lost");
        } else if receipt_seen {
            info!("[reliable-paste] settling: reads went quiet");
        } else if injection_failed {
            info!("[reliable-paste] settling: chord injection failed, restoring quickly");
        } else {
            info!("[reliable-paste] settling: no read within timeout, restoring anyway");
        }

        let pending_for_finish = pending.clone();
        let app_for_finish = app_handle.clone();
        let _ = app_handle.run_on_main_thread(move || {
            settle(&pending_for_finish, &app_for_finish, None);
            if let Ok(mut slot) = PENDING.lock() {
                let is_us = slot
                    .as_ref()
                    .map(|current| Arc::ptr_eq(current, &pending))
                    .unwrap_or(false);
                if is_us {
                    *slot = None;
                }
            }
        });
    });
}

pub(super) fn run(
    text: &str,
    app_handle: &AppHandle,
    paste_method: &PasteMethod,
    enigo: &mut enigo::Enigo,
    auto_submit: bool,
    auto_submit_key: AutoSubmitKey,
    clipboard_handling: ClipboardHandling,
) -> Result<(), String> {
    // 旧语音调用者仅在未发键时允许其原有 fallback。发键失败不能被伪装成启动失败。
    match run_inner(
        text,
        app_handle,
        paste_method,
        enigo,
        PasteCompletion {
            auto_submit,
            auto_submit_key,
            clipboard_handling,
        },
        &mut || Ok(()),
    ) {
        HistoryPasteOutcome::NotDispatched(error) => Err(error),
        HistoryPasteOutcome::PossiblyDispatched(error) => {
            error!("[reliable-paste] injection outcome uncertain: {error}");
            Ok(())
        }
        HistoryPasteOutcome::Dispatched => Ok(()),
    }
}

pub(super) fn run_history(
    text: &str,
    app_handle: &AppHandle,
    paste_method: &PasteMethod,
    enigo: &mut enigo::Enigo,
    validate: &mut dyn FnMut() -> Result<(), String>,
) -> HistoryPasteOutcome {
    // 不通过 flush 旧事务向新目标补发旧 auto-submit，也不提前恢复尚未读完的内容。
    // 主线程串行进入；忙碌只是本次未派发，旧事务仍按原有 receipt/timeout 完成。
    match PENDING.try_lock() {
        Ok(slot) => {
            if let Some(pending) = slot.as_ref() {
                match pending.try_lock() {
                    Ok(pending) if pending.settled => {}
                    _ => {
                        return HistoryPasteOutcome::NotDispatched(
                            "clipboard transaction pending".into(),
                        )
                    }
                }
            }
        }
        Err(_) => return HistoryPasteOutcome::NotDispatched("clipboard transaction busy".into()),
    }
    run_inner(
        text,
        app_handle,
        paste_method,
        enigo,
        PasteCompletion {
            auto_submit: false,
            auto_submit_key: AutoSubmitKey::Enter,
            clipboard_handling: ClipboardHandling::DontModify,
        },
        validate,
    )
}

fn run_inner(
    text: &str,
    app_handle: &AppHandle,
    paste_method: &PasteMethod,
    enigo: &mut enigo::Enigo,
    completion: PasteCompletion,
    validate: &mut dyn FnMut() -> Result<(), String>,
) -> HistoryPasteOutcome {
    let permission_epoch = match crate::input_permission::capture_epoch() {
        Ok(epoch) => epoch,
        Err(error) => return HistoryPasteOutcome::NotDispatched(error),
    };
    let mut permission_validate = || {
        crate::input_permission::check_epoch(permission_epoch)?;
        validate()
    };
    let validate: &mut dyn FnMut() -> Result<(), String> = &mut permission_validate;
    let PasteCompletion {
        auto_submit,
        auto_submit_key,
        clipboard_handling,
    } = completion;
    if let Err(error) = validate() {
        return HistoryPasteOutcome::NotDispatched(error);
    }
    // Settle any previous transaction first so the snapshot below captures the
    // user's original clipboard, not the previous transcript.
    flush_pending(app_handle, enigo);

    let pasteboard = NSPasteboard::generalPasteboard();
    let snapshot = match snapshot(&pasteboard) {
        Ok(snapshot) => snapshot,
        Err(error) => return HistoryPasteOutcome::NotDispatched(error),
    };

    let state = Arc::new(Mutex::new(TxState::new()));
    let provider = HandyPasteProvider::new(state.clone(), text.to_string());

    let mut types: Vec<Retained<NSString>> = Vec::with_capacity(1 + CONCEALMENT_TYPES.len());
    types.push(NSString::from_str("public.utf8-plain-text"));
    for t in CONCEALMENT_TYPES {
        types.push(NSString::from_str(t));
    }
    let types = NSArray::from_retained_slice(&types);

    // 延迟表示兑现可能很慢；快照之后重新检查，不向已经改变的目标发键。
    if let Err(error) = validate() {
        return HistoryPasteOutcome::NotDispatched(error);
    }
    if pasteboard.changeCount() != snapshot.change_count {
        return HistoryPasteOutcome::NotDispatched("clipboard changed before publish".into());
    }

    // declareTypes:owner: clears the pasteboard and puts our promise on it;
    // the return value is the new changeCount.
    let change_count: NSInteger =
        unsafe { msg_send![&*pasteboard, declareTypes: &*types, owner: &*provider] };
    if change_count <= 0 {
        return HistoryPasteOutcome::NotDispatched("declareTypes:owner: failed".to_string());
    }
    info!("[reliable-paste] published transcript as lazy promise (changeCount {change_count})");

    let outcome = guarded_dispatch(validate, || {
        if pasteboard.changeCount() != change_count {
            // 在此闭包中的失败一律保守当作可能派发；实际未发键仍不自动重试。
            return Err("clipboard changed before paste chord".into());
        }
        if let Ok(mut st) = state.lock() {
            st.injected_at = Some(Instant::now());
        }
        send_chord(enigo, paste_method)
    });
    match &outcome {
        HistoryPasteOutcome::Dispatched => {
            info!("[reliable-paste] paste chord sent ({paste_method:?})");
        }
        HistoryPasteOutcome::NotDispatched(e) | HistoryPasteOutcome::PossiblyDispatched(e) => {
            // Keep the transaction alive: the waiter restores the clipboard
            // after the short failed-injection timeout.
            if let Ok(mut st) = state.lock() {
                st.injection_failed = true;
            }
            error!("[reliable-paste] failed to send paste chord: {e}");
        }
    }

    let pending = Arc::new(Mutex::new(MacPending {
        permission_epoch,
        state,
        snapshot,
        change_count,
        provider: Some(provider),
        auto_submit,
        auto_submit_key,
        preserve_transcript: clipboard_handling == ClipboardHandling::CopyToClipboard,
        transcript: text.to_string(),
        settled: false,
    }));
    if let Ok(mut slot) = PENDING.lock() {
        *slot = Some(pending.clone());
    }
    spawn_waiter(pending, app_handle.clone());

    outcome
}

/// 主线程上的独立命名板检查，不读取或改写 generalPasteboard。
pub(crate) fn private_pasteboard_self_check() -> Result<(), String> {
    if objc2::MainThreadMarker::new().is_none() {
        return Err("private clipboard diagnostic requires main thread".into());
    }
    struct PrivateBoard(Retained<NSPasteboard>);
    impl Drop for PrivateBoard {
        fn drop(&mut self) {
            self.0.clearContents();
        }
    }
    let board = PrivateBoard(NSPasteboard::pasteboardWithUniqueName());
    let initial = ClipboardSnapshot {
        change_count: board.0.changeCount(),
        items: vec![
            vec![
                (
                    "public.utf8-plain-text".into(),
                    "合成测试".as_bytes().to_vec(),
                ),
                ("public.html".into(), b"<b>synthetic</b>".to_vec()),
                ("public.rtf".into(), b"{\\rtf1 synthetic}".to_vec()),
            ],
            vec![
                (
                    "public.file-url".into(),
                    b"file:///tmp/synthetic-only.pdf".to_vec(),
                ),
                ("test.binary.format".into(), vec![0, 255, 12]),
            ],
        ],
    };
    if publish_snapshot_on(&board.0, initial.clone(), || Ok(())) != HistoryPasteOutcome::Dispatched
    {
        return Err("private clipboard initial publication failed".into());
    }
    let saved = snapshot(&board.0)?;
    // 系统可以补充派生类型；每个原始 item/type 必须仍存在且逐字节相等。
    if saved.items.len() != initial.items.len()
        || !initial
            .items
            .iter()
            .zip(&saved.items)
            .all(|(original, observed)| original.iter().all(|entry| observed.contains(entry)))
    {
        return Err("private clipboard lost original representation".into());
    }
    let replacement = ClipboardSnapshot {
        change_count: board.0.changeCount(),
        items: vec![vec![(
            "public.utf8-plain-text".into(),
            b"temporary".to_vec(),
        )]],
    };
    if publish_snapshot_on(&board.0, replacement, || Ok(())) != HistoryPasteOutcome::Dispatched {
        return Err("private clipboard temporary publication failed".into());
    }
    if !restore_snapshot(&board.0, &saved, board.0.changeCount())?
        || snapshot(&board.0)?.items != saved.items
    {
        return Err("private clipboard restore differs from captured full snapshot".into());
    }
    let pending = ClipboardSnapshot {
        change_count: board.0.changeCount(),
        ..initial
    };
    if !matches!(
        publish_snapshot_on(&board.0, pending.clone(), || Err("revoked".into())),
        HistoryPasteOutcome::NotDispatched(_)
    ) || board.0.changeCount() != pending.change_count
    {
        return Err("revoked private clipboard publication changed content".into());
    }
    let outcome = publish_snapshot_on(&board.0, pending.clone(), || {
        board.0.clearContents();
        if !board
            .0
            .setString_forType(&NSString::from_str("new synthetic copy"), unsafe {
                NSPasteboardTypeString
            })
        {
            return Err("unable to simulate newer private copy".into());
        }
        Ok(())
    });
    let newer = snapshot(&board.0)?;
    if !matches!(outcome, HistoryPasteOutcome::NotDispatched(_))
        || restore_snapshot(&board.0, &pending, pending.change_count)?
        || snapshot(&board.0)? != newer
    {
        return Err("intervening private clipboard copy was overwritten".into());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn native_in_memory_items_preserve_raw_representations_without_touching_pasteboard() {
        let snapshot = ClipboardSnapshot {
            change_count: 1,
            items: vec![
                vec![
                    ("public.utf8-plain-text".into(), b"report".to_vec()),
                    ("public.html".into(), b"<b>report</b>".to_vec()),
                    ("public.rtf".into(), b"{\\rtf1 report}".to_vec()),
                    ("custom.zero-length".into(), Vec::new()),
                ],
                vec![
                    ("public.file-url".into(), b"file:///tmp/report.pdf".to_vec()),
                    ("public.png".into(), vec![0, 255, 3, 4]),
                ],
            ],
        };
        // 只创建独立内存对象，不取得 generalPasteboard 或任何命名剪贴板。
        let prepared = prepare_items(&snapshot).unwrap();
        assert_eq!(prepared.len(), snapshot.items.len());
        for (item, expected) in prepared.iter().zip(&snapshot.items) {
            assert_eq!(item.types().len(), expected.len());
            for (kind, bytes) in expected {
                assert_eq!(
                    item.dataForType(&NSString::from_str(kind))
                        .unwrap()
                        .to_vec(),
                    *bytes
                );
            }
        }
    }
}
