import { copyFileSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..");
const tauriDir = path.join(repoRoot, "src-tauri");
const helperName =
  process.platform === "win32"
    ? "handy-qwen-custom-words.exe"
    : "handy-qwen-custom-words";
// 发布构建为每次事务隔离 Cargo target；开发构建未设置时继续使用
// src-tauri/target。Cargo 会读取同一个环境变量决定实际输出目录。
const targetDir = process.env.CARGO_TARGET_DIR
  ? path.resolve(tauriDir, process.env.CARGO_TARGET_DIR)
  : path.join(tauriDir, "target");
const resourceDir = path.join(tauriDir, "resources", "qwen-helper");

mkdirSync(resourceDir, { recursive: true });
writeFileSync(
  path.join(resourceDir, ".keep"),
  "Generated by scripts/prepare-qwen-helper.ts\n",
);

const build = spawnSync(
  "cargo",
  ["build", "--release", "--bin", "handy-qwen-custom-words"],
  {
    cwd: tauriDir,
    stdio: "inherit",
  },
);

if (build.status !== 0) {
  process.exit(build.status ?? 1);
}

const source = path.join(targetDir, "release", helperName);
if (!existsSync(source)) {
  throw new Error(`Qwen helper binary was not built: ${source}`);
}

const destination = path.join(resourceDir, helperName);
copyFileSync(source, destination);
console.log(`Prepared Qwen helper resource: ${destination}`);
