import { copyFileSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..");
const tauriDir = path.join(repoRoot, "src-tauri");
const helperName =
  process.platform === "win32"
    ? "handy-qwen-custom-words.exe"
    : "handy-qwen-custom-words";
const resourceDir = path.join(tauriDir, "resources", "qwen-helper");

mkdirSync(resourceDir, { recursive: true });
writeFileSync(
  path.join(resourceDir, ".keep"),
  "Generated by scripts/prepare-qwen-helper.ts\n",
);

const build = spawnSync(
  "cargo",
  ["build", "--release", "--bin", "handy-qwen-custom-words"],
  {
    cwd: tauriDir,
    stdio: "inherit",
  },
);

if (build.status !== 0) {
  process.exit(build.status ?? 1);
}

const source = path.join(tauriDir, "target", "release", helperName);
if (!existsSync(source)) {
  throw new Error(`Qwen helper binary was not built: ${source}`);
}

const destination = path.join(resourceDir, helperName);
copyFileSync(source, destination);
console.log(`Prepared Qwen helper resource: ${destination}`);
