#!/bin/zsh
set -eu
set -o pipefail

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"

/usr/bin/python3 - "$ROOT_DIR" <<'PY'
from pathlib import Path
import sys

root = Path(sys.argv[1])


def read(name: str) -> str:
    return (root / name).read_text(encoding="utf-8")


def read_repo(name: str) -> str:
    return (root.parent.parent / name).read_text(encoding="utf-8")


def require(condition: bool, reason: str) -> None:
    if not condition:
        print(f"validationPolicySelfCheck=false reason={reason}")
        raise SystemExit(1)


dev_fast = read("dev-fast.sh")
rime_latency = read("rime-latency-self-check.sh")
verify_nongui = read("verify-nongui.sh")
install_check = read("install-check.sh")
install_handoff = read("install-handoff.sh")
apply_current_handoff = read("apply-current-handoff.sh")
repair_tis_duplicates = read("repair-tis-duplicates.sh")
build = read("build.sh")
verify_pkg = read("verify-pkg.sh")
settings_launcher_self_check = read("settings-launcher-build-self-check.sh")
schema_catalog_self_check = read("schema-catalog-self-check.sh")
settings_contract_self_check = read("settings-contract-self-check.sh")
full_check = read("release/full-check.sh")
candidate_panel = read("Sources/InputiaInputMethod/InputiaCandidatePanel.swift")
candidate_panel_self_check = read("Tools/InputiaCandidatePanelSelfCheck.swift")
settings_window_self_check = read("Tools/InputiaSettingsWindowSelfCheck.swift")
host_policy = read("Sources/InputiaInputMethod/InputiaHostTextPolicy.swift")
host_main = read("Sources/InputiaInputMethod/main.swift")
host_policy_self_check = read("Tools/InputiaHostTextPolicySelfCheck.swift")
menu_readiness = read("menu-readiness.sh")
gui_readiness = read("gui-smoke-readiness.sh")
gui_suite = read("gui-smoke-suite.sh")
status = read("status.sh")
post_install = read("post-install-regression.sh")
tis = read("tis-readiness.sh")
inputia_readme = read("README.md")
agents = read_repo("AGENTS.md")

require('Inputia macOS 验证分层' in agents, "agents-missing-inputia-validation-tier-section")
require('./macos/InputiaInputMethod/dev-fast.sh' in agents, "agents-missing-dev-fast-command")
require('./macos/InputiaInputMethod/install-check.sh' in agents, "agents-missing-install-check-command")
require('./macos/InputiaInputMethod/release/full-check.sh' in agents, "agents-missing-full-check-command")
require('不得打开菜单栏' in agents, "agents-missing-no-menu-policy")
require('不得打开 GUI' in agents, "agents-missing-no-gui-policy")
require('不得改系统输入源' in agents, "agents-missing-no-input-source-policy")
require('不得检查公证' in agents, "agents-missing-no-notarization-policy")
require('INPUTIA_MENU_READINESS_CACHE_FILE' in agents, "agents-missing-menu-cache-policy")

require('普通开发默认验证' in inputia_readme, "readme-missing-dev-fast-section")
require('安装链路变化后的验证' in inputia_readme, "readme-missing-install-check-section")
require('发布前或安装脚本变化后的完整验证' in inputia_readme, "readme-missing-full-check-section")
require('`dev-fast.sh` 是候选词、双拼、快捷键、设置 UI 等日常开发的默认入口' in inputia_readme, "readme-missing-dev-fast-default-contract")
require('`release/full-check.sh` 是显式 opt-in 的重型入口' in inputia_readme, "readme-missing-full-check-opt-in-contract")
require('让菜单栏 AXPress 最多执行一次' in inputia_readme, "readme-missing-menu-cache-contract")

require('validationTier=dev-fast' in dev_fast, "dev-fast-missing-tier-marker")
require('touchesMenuBar=false' in dev_fast, "dev-fast-missing-menu-policy")
require('opensGUI=false' in dev_fast, "dev-fast-missing-gui-policy")
require('changesSystemInputSource=false' in dev_fast, "dev-fast-missing-input-source-policy")
require('checksNotarization=false' in dev_fast, "dev-fast-missing-notarization-policy")
require('"$ROOT_DIR/validation-policy-self-check.sh"' in dev_fast, "dev-fast-missing-policy-self-check")
require('"$ROOT_DIR/rime-latency-self-check.sh"' in dev_fast, "dev-fast-missing-rime-latency-self-check")
require('"$ROOT_DIR/settings-launcher-build-self-check.sh"' in dev_fast, "dev-fast-missing-settings-launcher-build-self-check")
require('"$ROOT_DIR/schema-catalog-self-check.sh"' in dev_fast, "dev-fast-missing-schema-catalog-self-check")
require('"$ROOT_DIR/settings-contract-self-check.sh"' in dev_fast, "dev-fast-missing-settings-contract-self-check")
require('"$ROOT_DIR/build/inputia-candidate-panel-self-check"' in dev_fast, "dev-fast-missing-candidate-panel-self-check")
require('"$ROOT_DIR/build/inputia-settings-window-self-check"' in dev_fast, "dev-fast-missing-settings-window-self-check")
require('schemaCatalogSelfCheck=true' in schema_catalog_self_check, "schema-catalog-self-check-missing-pass-marker")
require('settings-window-schema-list-mismatch' in schema_catalog_self_check, "schema-catalog-self-check-missing-settings-list-assertion")
require('capi-settings-schema-list-mismatch' in schema_catalog_self_check, "schema-catalog-self-check-missing-capi-list-assertion")
require('schema-smoke-missing:' in schema_catalog_self_check, "schema-catalog-self-check-missing-smoke-assertion")
require('rime-data-missing:' in schema_catalog_self_check, "schema-catalog-self-check-missing-rime-data-assertion")
require('settingsContractSelfCheck=' in settings_contract_self_check, "settings-contract-self-check-missing-pass-marker")
require('settingsContractSchemaDefaultMatches' in settings_contract_self_check, "settings-contract-self-check-missing-schema-assertion")
require('settingsContractSensitiveBundleIdsMatch' in settings_contract_self_check, "settings-contract-self-check-missing-sensitive-assertion")
require('settingsContractPathsMatch' in settings_contract_self_check, "settings-contract-self-check-missing-path-assertion")
require('settingsWindowSelfCheck=\\(ok)' in settings_window_self_check, "settings-window-self-check-missing-pass-marker")
require('settingsWindowSchemaCount=\\(inputiaSchemaOptions.count)' in settings_window_self_check, "settings-window-self-check-missing-schema-count")
require('settingsWindowDefaultCandidateCount=\\(inputiaSettingsDefaultCandidatePageSize)' in settings_window_self_check, "settings-window-self-check-missing-candidate-count-output")
require('settingsWindowHasGuobiaoBispell' in settings_window_self_check, "settings-window-self-check-missing-guobiao-assertion")
require('settingsWindowHasSogouDoublePinyin' in settings_window_self_check, "settings-window-self-check-missing-sogou-assertion")
require('settingsWindowTitleHasNoSimplifiedSuffix' in settings_window_self_check, "settings-window-self-check-missing-title-assertion")
require('settingsMenuKeyEquivalent = ""' in host_policy, "host-policy-settings-menu-key-equivalent-not-empty")
require('keyEquivalent: InputiaHostTextPolicy.settingsMenuKeyEquivalent' in host_main, "host-menu-settings-key-equivalent-not-policy-owned")
require('NSMenuItem(title: "Inputia 设置...", action: #selector(openSettings), keyEquivalent: ",")' not in host_main, "host-menu-settings-steals-command-comma")
require('settingsFingerprint' in read("Sources/InputiaInputMethod/InputiaRustBridge.swift"), "bridge-missing-settings-fingerprint")
require('currentFingerprint != settingsFingerprint' in read("Sources/InputiaInputMethod/InputiaRustBridge.swift"), "bridge-reload-still-mtime-only")
require('settingsReloadNoOpReloaded=' in host_main, "host-diagnostics-missing-noop-reload-output")
require('settingsReloadNoOpPreservedComposing=' in host_main, "host-diagnostics-missing-noop-composition-output")
require('"$HOST_EXEC" --bridge-settings-reload-self-check' in dev_fast, "dev-fast-missing-settings-reload-self-check")
require('settingsMenuHasNoCommandKeyEquivalent' in host_policy_self_check, "host-policy-self-check-missing-settings-menu-key")
require('showPreferencesCommandPassesThrough' in host_policy_self_check, "host-policy-self-check-missing-show-preferences")
require('emptyNewlineCommandPassesThrough' in host_policy_self_check, "host-policy-self-check-missing-empty-newline")
require('emptyLineBreakCommandPassesThrough' in host_policy_self_check, "host-policy-self-check-missing-empty-line-break")
require('composingNewlineCommandIsHandled' in host_policy_self_check, "host-policy-self-check-missing-composing-newline")
require('composingLineBreakCommandIsHandled' in host_policy_self_check, "host-policy-self-check-missing-composing-line-break")
for forbidden in [
    "menu-readiness.sh",
    "gui-smoke-readiness.sh",
    "gui-smoke-suite.sh",
    "post-install-regression.sh",
    "status.sh",
    "notarization-readiness.sh",
    "smoke-textedit.sh",
    "smoke-safari-typing.sh",
    "smoke-clipboard-recall.sh",
]:
    require(forbidden not in dev_fast, f"dev-fast-unexpected-{forbidden}")

require('verifyNonguiCompatibilityMode=dev-fast' in verify_nongui, "verify-nongui-not-dev-fast-compatible")
require('exec "$ROOT_DIR/dev-fast.sh" "$@"' in verify_nongui, "verify-nongui-default-does-not-exec-dev-fast")
require('INPUTIA_VERIFY_NONGUI_FULL:-0' in verify_nongui, "verify-nongui-missing-full-opt-in")
require('verifyNonguiMenuReadinessCacheFile=' in verify_nongui, "verify-nongui-full-missing-menu-cache-output")
require('INPUTIA_MENU_READINESS_CACHE_FILE' in verify_nongui, "verify-nongui-full-missing-menu-cache")
require('VERIFY_TEMP_FILES+=("$INPUTIA_MENU_READINESS_CACHE_FILE")' in verify_nongui, "verify-nongui-full-menu-cache-not-cleaned")
require('INPUTIA_MENU_READINESS_ALLOW_AXPRESS="${INPUTIA_MENU_READINESS_ALLOW_AXPRESS:-0}"' in verify_nongui, "verify-nongui-menu-readiness-not-explicit-opt-in")
require('INPUTIA_GUI_SMOKE_READINESS_ALLOW_CHECK="${INPUTIA_GUI_SMOKE_READINESS_ALLOW_CHECK:-0}"' in verify_nongui, "verify-nongui-gui-readiness-not-explicit-opt-in")
require('INPUTIA_STATUS_INCLUDE_MENU_READINESS="${INPUTIA_STATUS_INCLUDE_MENU_READINESS:-0}"' in verify_nongui, "verify-nongui-status-menu-not-explicit-opt-in")
require('INPUTIA_STATUS_INCLUDE_GUI_SMOKE_READINESS="${INPUTIA_STATUS_INCLUDE_GUI_SMOKE_READINESS:-0}"' in verify_nongui, "verify-nongui-status-gui-not-explicit-opt-in")
require('INPUTIA_TIS_INCLUDE_MENU_READINESS="${INPUTIA_TIS_INCLUDE_MENU_READINESS:-0}"' in verify_nongui, "verify-nongui-tis-menu-not-explicit-opt-in")
require('verifyNonguiMenuReadinessOptIn=' in verify_nongui, "verify-nongui-missing-menu-opt-in-output")
require('verifyNonguiGuiReadinessOptIn=' in verify_nongui, "verify-nongui-missing-gui-opt-in-output")
require('INPUTIA_MENU_READINESS_ALLOW_AXPRESS="${INPUTIA_MENU_READINESS_ALLOW_AXPRESS:-1}"' not in verify_nongui, "verify-nongui-menu-readiness-defaults-on")
require('INPUTIA_GUI_SMOKE_READINESS_ALLOW_CHECK="${INPUTIA_GUI_SMOKE_READINESS_ALLOW_CHECK:-1}"' not in verify_nongui, "verify-nongui-gui-readiness-defaults-on")
require('INPUTIA_STATUS_INCLUDE_GUI_SMOKE_READINESS="${INPUTIA_STATUS_INCLUDE_GUI_SMOKE_READINESS:-1}"' not in verify_nongui, "verify-nongui-status-gui-defaults-on")
require(
    verify_nongui.index('INPUTIA_MENU_READINESS_CACHE_FILE') < verify_nongui.index('INPUTIA_MENU_READINESS_ALLOW_AXPRESS'),
    "verify-nongui-menu-cache-after-axpress-opt-in",
)

require('validationTier=install-check' in install_check, "install-check-missing-tier-marker")
require('INPUTIA_TIS_INCLUDE_MENU_READINESS=0 "$ROOT_DIR/tis-readiness.sh"' in install_check, "install-check-must-disable-menu-readiness")
require('installCheckBlockReasons=' in install_check, "install-check-missing-block-reasons")
require('installCheckRequiredAction=' in install_check, "install-check-missing-required-action")
require('installCheckRequiredActions=' in install_check, "install-check-missing-required-actions")
require('installCheckNextStep=' in install_check, "install-check-missing-next-step")
require('installCheckNextCommand=' in install_check, "install-check-missing-next-command")
require('installCheckRequiredCommands=present' in install_check, "install-check-missing-required-commands-present")
require('installCheckCommand.runInstallHandoff=' in install_check, "install-check-missing-handoff-command-output")
require('installCheckCommand.adminInstall=' in install_check, "install-check-missing-admin-install-command-output")
require('installCheckCommand.repairTISDuplicates=' in install_check, "install-check-missing-repair-command-output")
require('installCheckCommand.awaitSystemInstall=' in install_check, "install-check-missing-await-command-output")
require('installCheckCommand.verify=' in install_check, "install-check-missing-verify-command-output")
require('installCheckCommand.applyCurrentHandoff=' in install_check, "install-check-missing-apply-current-handoff-command-output")
require('installHandoffCurrent=' in install_check, "install-check-missing-handoff-current")
require('installHandoffBlockReasons=' in install_check, "install-check-missing-handoff-block-reasons")
require('installHandoffRequiredAction=run-install-handoff' in install_check, "install-check-missing-handoff-required-action")
require('source-commit-mismatch' in install_check, "install-check-missing-handoff-source-commit-mismatch")
require('build-cdhash-mismatch' in install_check, "install-check-missing-handoff-build-cdhash-mismatch")
require('package-sha-mismatch' in install_check, "install-check-missing-handoff-package-sha-mismatch")
require('INPUTIA_INSTALL_CHECK_SELF_CHECK:-0' in install_check, "install-check-missing-self-check-mode")
require('installCheckSelfCheck=true' in install_check, "install-check-missing-self-check-pass-marker")
require('installHandoffFreshnessSelfCheck=true' in install_check, "install-check-missing-handoff-freshness-self-check")
require('installRequiredCommandsSelfCheck=true' in install_check, "install-check-missing-required-commands-self-check")
require('installNextStepSelfCheck=true' in install_check, "install-check-missing-next-step-self-check")
require('run-install-handoff-and-admin-install' in install_check, "install-check-missing-admin-required-action")
require('admin-install-current-handoff' in install_check, "install-check-missing-current-handoff-admin-action")
require('restart-inputia-host-after-install' in install_check, "install-check-missing-running-host-action")
require('apply-current-handoff' in install_check, "install-check-missing-apply-next-step")
require('open-keyboard-settings' in install_check, "install-check-missing-settings-next-step")
require('tis-duplicate-matches' in install_check, "install-check-missing-tis-duplicate-blocker")
require('remove-duplicate-inputia-and-readd-once' in install_check, "install-check-missing-tis-duplicate-action")
require('run-repair-tis-duplicates' in install_check, "install-check-missing-tis-duplicate-actions-chain")
require('actions-mismatch' in install_check, "install-check-self-check-missing-actions-assertion")
require('command-keys-mismatch' in install_check, "install-check-self-check-missing-command-assertion")
require('step-mismatch' in install_check, "install-check-self-check-missing-next-step-assertion")
require('buildSettingsExpectedHostCDHash=' in install_check, "install-check-missing-build-settings-expected-host-cdhash")
require('systemSettingsExpectedHostCDHash=' in install_check, "install-check-missing-system-settings-expected-host-cdhash")
require('"$system_settings_expected_host_cdhash" == "$build_cdhash"' in install_check, "install-check-settings-match-not-bound-to-host-cdhash")
require('InputiaSourceCommit' in build, "build-missing-source-commit-stamp")
require('InputiaSourceBranch' in build, "build-missing-source-branch-stamp")
require('InputiaSourceDirty' in build, "build-missing-source-dirty-stamp")
require('buildSourceCommit=' in install_check, "install-check-missing-build-source-commit")
require('systemSourceCommit=' in install_check, "install-check-missing-system-source-commit")
require('buildSettingsSourceCommit=' in install_check, "install-check-missing-build-settings-source-commit")
require('systemSettingsSourceCommit=' in install_check, "install-check-missing-system-settings-source-commit")
require('"$ROOT_DIR/install-check.sh"' in dev_fast, "dev-fast-missing-install-check-self-check")
require('INPUTIA_INSTALL_CHECK_SELF_CHECK=1 "$ROOT_DIR/install-check.sh"' in dev_fast, "dev-fast-install-check-not-self-check-only")
require('INPUTIA_APPLY_CURRENT_HANDOFF_SELF_CHECK=1 "$ROOT_DIR/apply-current-handoff.sh"' in dev_fast, "dev-fast-missing-apply-current-handoff-self-check")
require('INPUTIA_REPAIR_TIS_DUPLICATES_SELF_CHECK=1 "$ROOT_DIR/repair-tis-duplicates.sh"' in dev_fast, "dev-fast-missing-tis-duplicate-repair-self-check")
require('installCheckBlockReasons=' in install_handoff, "install-handoff-missing-block-reasons")
require('installCheckRequiredAction=' in install_handoff, "install-handoff-missing-required-action")
require('installCheckRequiredActions=' in install_handoff, "install-handoff-missing-required-actions")
require('installCheckPassed=' in install_handoff, "install-handoff-missing-install-check-pass")
require('settingsMatchesBuild=' in install_handoff, "install-handoff-missing-settings-match-summary")
require('buildSettingsExpectedHostCDHash=' in install_handoff, "install-handoff-missing-build-settings-host-cdhash")
require('systemSettingsExpectedHostCDHash=' in install_handoff, "install-handoff-missing-system-settings-host-cdhash")
require('applyCurrentHandoffCommand=' in install_handoff, "install-handoff-missing-apply-current-command")
require('推荐完整安装/修复/验证：' in install_handoff, "install-handoff-missing-recommended-apply-section")
require('INPUTIA_ALLOW_ADMIN_PROMPT=1 ./apply-current-handoff.sh' in install_handoff, "install-handoff-missing-apply-current-command-body")
require('sourceBranch=' in install_handoff, "install-handoff-missing-source-branch")
require('sourceCommit=' in install_handoff, "install-handoff-missing-source-commit")
require('sourceUpstream=' in install_handoff, "install-handoff-missing-source-upstream")
require('sourceDirty=' in install_handoff, "install-handoff-missing-source-dirty")
require('pkgVerificationPassed=' in install_handoff, "install-handoff-missing-pkg-verification")
require('repairTISDuplicatesRequired=' in install_handoff, "install-handoff-missing-duplicate-repair-summary")
require('INPUTIA_REPAIR_TIS_DUPLICATES=1 ./repair-tis-duplicates.sh' in install_handoff, "install-handoff-missing-duplicate-repair-command")
require(
    install_handoff.index('推荐完整安装/修复/验证：') < install_handoff.index('管理员终端安装：'),
    "install-handoff-apply-command-after-raw-installer",
)
require(
    install_handoff.index('INPUTIA_REPAIR_TIS_DUPLICATES=1 ./repair-tis-duplicates.sh') < install_handoff.index('$await_command'),
    "install-handoff-repair-command-after-await-command",
)
require('handoffOpensGUI=false' in install_handoff, "install-handoff-missing-no-gui-marker")
require('handoffChangesSystemInputSource=false' in install_handoff, "install-handoff-missing-no-input-source-marker")
require('successCriteria.installCheckBlockReasons=none' in install_handoff, "install-handoff-missing-success-criteria")
require('successCriteria.installCheckTISDuplicateMatches=false' in install_handoff, "install-handoff-missing-duplicate-success-criteria")
require('successCriteria.installCheckRequiredActions=none' in install_handoff, "install-handoff-missing-actions-success-criteria")
require('successCriteria.installCheckPassed=true' in install_handoff, "install-handoff-missing-passed-success-criteria")
require('successCriteria.systemMatchesBuild=true' in install_handoff, "install-handoff-missing-system-match-success-criteria")
require('successCriteria.settingsMatchesBuild=true' in install_handoff, "install-handoff-missing-settings-match-success-criteria")
require('successCriteria.runningMatchesBuild=true' in install_handoff, "install-handoff-missing-running-match-success-criteria")
for forbidden in [
    "menu-readiness.sh",
    "gui-smoke-readiness.sh",
    "gui-smoke-suite.sh",
    "INPUTIA_RUN_UI_SMOKE=1",
    "notarization-readiness.sh",
]:
    require(forbidden not in install_check, f"install-check-unexpected-{forbidden}")

require('validationTier=tis-duplicate-repair' in repair_tis_duplicates, "repair-tis-missing-tier-marker")
require('touchesMenuBar=false' in repair_tis_duplicates, "repair-tis-missing-menu-policy")
require('opensGUI=false' in repair_tis_duplicates, "repair-tis-missing-gui-policy")
require('INPUTIA_REPAIR_TIS_DUPLICATES:-0' in repair_tis_duplicates, "repair-tis-missing-opt-in-gate")
require('tisDuplicateRepairReady=false reason=opt-in-required' in repair_tis_duplicates, "repair-tis-missing-default-deny")
require('INPUTIA_REPAIR_TIS_READINESS_FOR_TEST' in repair_tis_duplicates, "repair-tis-missing-offline-self-check-readiness")
require('INPUTIA_REPAIR_SYSTEM_MATCHES_BUILD_FOR_TEST' in repair_tis_duplicates, "repair-tis-missing-system-match-self-check")
require('INPUTIA_REPAIR_INSTALL_CHECK_FOR_TEST' in repair_tis_duplicates, "repair-tis-missing-install-check-self-check")
require('tisDuplicateRepairReady=false reason=system-cdhash-mismatch' in repair_tis_duplicates, "repair-tis-missing-system-match-gate")
require('run-install-handoff-and-admin-install-before-repair' in repair_tis_duplicates, "repair-tis-missing-install-before-repair-action")
require('admin-install-current-handoff-before-repair' in repair_tis_duplicates, "repair-tis-missing-current-handoff-install-before-repair-action")
require('--disable-all-inputia-sources' in repair_tis_duplicates, "repair-tis-missing-disable-all-command")
require('--register-input-source' in repair_tis_duplicates, "repair-tis-missing-register-command")
require('--enable-input-source' in repair_tis_duplicates, "repair-tis-missing-enable-command")
require('--select-input-source' in repair_tis_duplicates, "repair-tis-missing-select-command")
require('INPUTIA_REPAIR_TIS_DUPLICATES_SELF_CHECK' in repair_tis_duplicates, "repair-tis-missing-self-check")
require('INPUTIA_REPAIR_TIS_DUPLICATES=1 "$ROOT_DIR/repair-tis-duplicates.sh"' not in dev_fast, "dev-fast-unexpected-real-repair-tis")
require('"$ROOT_DIR/repair-tis-duplicates.sh"' not in install_check, "install-check-unexpected-executed-repair-tis")

require('validationTier=install-apply' in apply_current_handoff, "apply-current-handoff-missing-tier-marker")
require('touchesMenuBar=false' in apply_current_handoff, "apply-current-handoff-missing-menu-policy")
require('opensGUI=false' in apply_current_handoff, "apply-current-handoff-missing-gui-policy")
require('checksNotarization=false' in apply_current_handoff, "apply-current-handoff-missing-notarization-policy")
require('INPUTIA_APPLY_CURRENT_HANDOFF_SELF_CHECK' in apply_current_handoff, "apply-current-handoff-missing-self-check")
require('INPUTIA_APPLY_FINAL_INSTALL_CHECK_FOR_TEST' in apply_current_handoff, "apply-current-handoff-missing-final-check-self-test")
require('applyCurrentHandoffPassed=false reason=final-install-check-failed' in apply_current_handoff, "apply-current-handoff-missing-final-failure-marker")
require('applyCurrentHandoffFinalInstallCheckExit=' in apply_current_handoff, "apply-current-handoff-missing-final-check-exit-output")
require('applyCurrentHandoffNextStep=' in apply_current_handoff, "apply-current-handoff-missing-final-next-step-output")
require('INPUTIA_ALLOW_ADMIN_PROMPT=1 ./apply-current-handoff.sh' in apply_current_handoff, "apply-current-handoff-missing-admin-prompt-command")
require('INPUTIA_REPAIR_TIS_DUPLICATES=1 "$ROOT_DIR/repair-tis-duplicates.sh"' in apply_current_handoff, "apply-current-handoff-missing-repair-command")
require('"$ROOT_DIR/await-system-install.sh"' in apply_current_handoff, "apply-current-handoff-missing-await-command")
require('"$ROOT_DIR/install-check.sh"' in apply_current_handoff, "apply-current-handoff-missing-final-install-check")
require('INPUTIA_ALLOW_ADMIN_PROMPT=1 "$ROOT_DIR/apply-current-handoff.sh"' not in dev_fast, "dev-fast-unexpected-real-apply-current-handoff")

require('InputiaCandidatePanelFormatter' in candidate_panel, "candidate-panel-missing-formatter")
require('maximumCandidateCount = 9' in candidate_panel, "candidate-panel-missing-nine-candidate-cap")
require('expanded ? "\\n" : "   "' in candidate_panel, "candidate-panel-missing-expanded-line-break")
require('InputiaCandidatePanelFormatter.candidateString' in candidate_panel, "candidate-panel-show-not-using-formatter")
require('InputiaCandidatePanelSelfCheck.swift' in build, "build-missing-candidate-panel-self-check-tool")
require('inputia-candidate-panel-self-check' in build, "build-missing-candidate-panel-self-check-output")
require('InputiaExpectedHostCDHash' in build, "build-missing-settings-launcher-expected-host-cdhash")
require('settingsLauncherBuildSelfCheck=true' in settings_launcher_self_check, "settings-launcher-self-check-missing-pass-marker")
require('expected-host-cdhash-mismatch' in settings_launcher_self_check, "settings-launcher-self-check-missing-cdhash-mismatch")
require('InputiaExpectedHostCDHash' in settings_launcher_self_check, "settings-launcher-self-check-missing-expected-host-cdhash")
require('settingsLauncherHostSourceCommit=' in settings_launcher_self_check, "settings-launcher-self-check-missing-host-source-commit")
require('settings-source-commit-mismatch' in settings_launcher_self_check, "settings-launcher-self-check-missing-source-commit-check")
require('bundleCDHash(at:' in read("SettingsLauncher/main.swift"), "settings-launcher-source-missing-cdhash-check")
require('build-settings-expected-host-cdhash-mismatch' in verify_pkg, "verify-pkg-missing-build-settings-host-cdhash-check")
require('archive-settings-expected-host-cdhash-mismatch' in verify_pkg, "verify-pkg-missing-archive-settings-host-cdhash-check")
require('archiveSettingsExpectedHostCDHash=' in verify_pkg, "verify-pkg-missing-archive-settings-host-cdhash-output")
require('buildSettingsExpectedHostCDHash=' in verify_pkg, "verify-pkg-missing-build-settings-host-cdhash-output")
require('archiveSourceCommit=' in verify_pkg, "verify-pkg-missing-archive-source-commit-output")
require('archive-source-commit-mismatch' in verify_pkg, "verify-pkg-missing-archive-source-commit-check")
require('archive-settings-source-commit-mismatch' in verify_pkg, "verify-pkg-missing-settings-source-commit-check")
require('candidatePanelSelfCheck=' in candidate_panel_self_check, "candidate-panel-self-check-missing-pass-marker")
require('candidatePanelExpandedBreaksLines' in candidate_panel_self_check, "candidate-panel-self-check-missing-expanded-lines-case")
require('candidatePanelCollapsedContainsSeventhCandidate' in candidate_panel_self_check, "candidate-panel-self-check-missing-seventh-candidate-case")
require('candidatePanelExpandedCapsAtNineCandidates' in candidate_panel_self_check, "candidate-panel-self-check-missing-cap-case")

require('validationTier=release/full-check' in full_check, "full-check-missing-tier-marker")
require('touchesMenuBar=true' in full_check, "full-check-missing-menu-policy")
require('opensGUI=true' in full_check, "full-check-missing-gui-policy")
require('checksNotarization=true' in full_check, "full-check-missing-notarization-policy")
require('INPUTIA_MENU_READINESS_CACHE_FILE="$MENU_CACHE"' in full_check, "full-check-missing-menu-cache")
require('INPUTIA_MENU_READINESS_ALLOW_AXPRESS=1' in full_check, "full-check-missing-menu-opt-in")
require('INPUTIA_GUI_SMOKE_READINESS_ALLOW_CHECK=1' in full_check, "full-check-missing-gui-readiness-opt-in")
require('INPUTIA_RUN_UI_SMOKE=1' in full_check, "full-check-missing-ui-smoke-opt-in")
require('"$ROOT_DIR/menu-readiness.sh"' in full_check, "full-check-missing-menu-readiness")
require(full_check.count('"$ROOT_DIR/menu-readiness.sh"') == 1, "full-check-menu-readiness-must-run-once-directly")
require(full_check.index('INPUTIA_MENU_READINESS_CACHE_FILE="$MENU_CACHE"') < full_check.index('"$ROOT_DIR/menu-readiness.sh"'), "full-check-menu-cache-after-menu-readiness")
require(full_check.index('INPUTIA_MENU_READINESS_CACHE_FILE="$MENU_CACHE"') < full_check.index('"$ROOT_DIR/post-install-regression.sh" "$APP"'), "full-check-menu-cache-after-postinstall")
require('"$ROOT_DIR/post-install-regression.sh" "$APP"' in full_check, "full-check-missing-postinstall-regression")
require('"$ROOT_DIR/notarization-readiness.sh"' in full_check, "full-check-missing-notarization-readiness")

require('INPUTIA_MENU_READINESS_ALLOW_AXPRESS:-0' in menu_readiness, "menu-readiness-missing-axpress-opt-in")
require('menuAXPressAllowed=false' in menu_readiness, "menu-readiness-missing-deny-marker")
require('menuReadinessBlockReason=opt-in-required' in menu_readiness, "menu-readiness-missing-opt-in-reason")
require('menuReadinessCache=hit' in menu_readiness, "menu-readiness-missing-cache-hit")
require(menu_readiness.index('menuReadinessCache=hit') < menu_readiness.index('/usr/bin/osascript'), "menu-readiness-cache-after-osascript")
require(menu_readiness.index('INPUTIA_MENU_READINESS_ALLOW_AXPRESS') < menu_readiness.index('/usr/bin/osascript'), "menu-readiness-gate-after-osascript")

require('INPUTIA_MENU_READINESS_ALLOW_AXPRESS=1 "$ROOT_DIR/menu-readiness.sh"' in status, "status-menu-opt-in-not-explicit")
require('INPUTIA_STATUS_INCLUDE_MENU_READINESS:-0' in status, "status-missing-menu-include-gate")
require('INPUTIA_STATUS_INCLUDE_GUI_SMOKE_READINESS:-0' in status, "status-missing-gui-readiness-gate")
require('INPUTIA_MENU_READINESS_CACHE_FILE="$menu_readiness_cache_file"' in status, "status-menu-readiness-missing-cache-env")
require('INPUTIA_VERIFICATION_OWNER_PID:-$$' in status, "status-menu-readiness-missing-owner-cache")
require('menuReadinessCacheFile=' in status, "status-menu-readiness-missing-cache-output")
require('statusGuiSmokeReady=unknown reason=skipped' in status, "status-default-gui-summary-not-skipped")
require('app_expected_host_cdhash' in status, "status-missing-settings-expected-host-helper")
require('targetSettingsExpectedHostCDHash=' in status, "status-missing-target-settings-expected-host-cdhash")
require('targetSettingsMatchesBuild=' in status, "status-missing-target-settings-build-match")
require('sourceCommit=' in status, "status-missing-source-commit-output")
require('sourceBranch=' in status, "status-missing-source-branch-output")
require('sourceDirty=' in status, "status-missing-source-dirty-output")

require('INPUTIA_MENU_READINESS_ALLOW_AXPRESS=1 "$ROOT_DIR/menu-readiness.sh"' in tis, "tis-menu-opt-in-not-explicit")
require('INPUTIA_TIS_INCLUDE_MENU_READINESS:-0' in tis, "tis-missing-menu-include-gate")
require('INPUTIA_MENU_READINESS_CACHE_FILE="$menu_readiness_cache_file"' in tis, "tis-menu-readiness-missing-cache-env")
require('INPUTIA_VERIFICATION_OWNER_PID:-$$' in tis, "tis-menu-readiness-missing-owner-cache")
require('tis.menuReadinessCacheFile=' in tis, "tis-menu-readiness-missing-cache-output")

require('INPUTIA_RUN_UI_SMOKE:-0' in post_install, "post-install-missing-ui-smoke-gate")
require('uiSmokeSkipped=true reason=disabled' in post_install, "post-install-missing-default-skip-marker")

require('rimeLatencyTouchesMenuBar=false' in rime_latency, "rime-latency-missing-menu-policy")
require('rimeLatencyOpensGUI=false' in rime_latency, "rime-latency-missing-gui-policy")
require('rimeLatencyChangesSystemInputSource=false' in rime_latency, "rime-latency-missing-input-source-policy")
require('rimeLatencyChecksNotarization=false' in rime_latency, "rime-latency-missing-notarization-policy")
require('persistent_session_probe' in rime_latency, "rime-latency-missing-persistent-probe")
require('rimeLatencySelfCheck=true' in rime_latency, "rime-latency-missing-pass-marker")
require('INPUTIA_RIME_LATENCY_MAX_INCREMENTAL_MS' in rime_latency, "rime-latency-missing-threshold-override")
require('INPUTIA_RIME_LATENCY_MIN_SPEEDUP' in rime_latency, "rime-latency-missing-speedup-override")

require('INPUTIA_GUI_SMOKE_READINESS_ALLOW_CHECK:-0' in gui_readiness, "gui-readiness-missing-opt-in")
require('guiSmokeReadinessOptInRequired=true' in gui_readiness, "gui-readiness-missing-opt-in-marker")
require('guiSmokeReadinessReady=false reason=opt-in-required' in gui_readiness, "gui-readiness-missing-opt-in-ready-line")
require('settings.buildExpectedHostCDHash=' in gui_readiness, "gui-readiness-missing-build-settings-host-cdhash")
require('settings.targetExpectedHostCDHash=' in gui_readiness, "gui-readiness-missing-target-settings-host-cdhash")
require('target_settings_expected_host_cdhash" == "$build_cdhash"' in gui_readiness, "gui-readiness-settings-match-not-bound-to-host-cdhash")

require('INPUTIA_RUN_UI_SMOKE:-0' in gui_suite, "gui-suite-missing-ui-smoke-gate")
require('INPUTIA_GUI_SMOKE_READINESS_ALLOW_CHECK=1' in gui_suite, "gui-suite-missing-readiness-opt-in")
require('guiSmokeSuiteReady=false reason=ui-smoke-opt-in-required' in gui_suite, "gui-suite-missing-opt-in-marker")

print("validationPolicySelfCheck=true")
PY
